### ISSUE TITLE
Silent errors when reading other compressed formats

### ISSUE THREAD

**Issue by afrubin** [lmdu/pyfastx#10]
Currently pyfastx checks to see if a file is gzip compressed, and if it is not it seems to interpret it as text. An unfortunate side effect of this is that if another compressed format is used, the program will happily return garbage reads:

```
>>> reads_1 = [x for x in pyfastx.Fastq("sample.fq.gz")]
>>> reads_1[:5]
[<Read> 140313_SN743_0432_AC3TTHACXX:4:1101:5633:2224:1#0/1 with length of 16,
 <Read> 140313_SN743_0432_AC3TTHACXX:4:1101:6580:2239:1#0/1 with length of 16,
 <Read> 140313_SN743_0432_AC3TTHACXX:4:1101:6929:2242:1#0/1 with length of 16,
 <Read> 140313_SN743_0432_AC3TTHACXX:4:1101:13004:2221:1#0/1 with length of 16,
 <Read> 140313_SN743_0432_AC3TTHACXX:4:1101:14034:2219:1#0/1 with length of 16]
```

```
>>> reads_2 = [x for x in pyfastx.Fastq("sample.fq.bz2")]
>>> reads_2[:5]
[<Read> Zh91AY&SY�7a�}^ with length of 4,
 <Read>  with length of 2,
 <Read>  with length of 257,
 <Read> Q4�TH�*�m�R�@�6�+� with length of 0,
 <Read> E��hĶ
  with length of 206]
```

Some basic error checking to make sure that the input file isn't in binary format, or perhaps a sterner warning in the README that this can happen, would be helpful!

**Comment by lmdu** [comment]
Thank you for your posting. In later version, I will add a validator to check input file is gzip compressed or other compressed format and give the appropriate prompt message.

**Comment by lmdu** [comment]
I added a simple validator for check format of input file in the latest version.
