### ISSUE TITLE
Can an index be "shared" by multiple processes?

### ISSUE THREAD

**Issue by nextgenusfs** [lmdu/pyfastx#14]
Thanks again for `pyfastx`, it is easy and fast to use.  I'm wondering if it is possible to generate an index from FASTQ file and if that index can be used by multiple processes at the same time, ie accessing different sequences from the index?  I've tried this and haven't gotten any exceptions/errors, however, the data is garbled coming back (mixture of seq and quality scores from a call to idx.seq).  I think I read somewhere in the docs that the index is SQLite3 database?

**Comment by lmdu** [comment]
Yes, the index file is just a SQLite3 database file. It can be used by multiple processes at the same time. Prior to reading sequences from multiple processes, you have to ensure index file has been created. There were two simple examples using pyfastx in multiprocessing.

Example one, building index in main process and create a new Fasta object for each subprocess.
```python
import random
import pyfastx
import multiprocessing as mp

# ensure index file has been created
_ = pyfastx.Fasta('test.fa')

# process worker
# randomly get five sequences and print
def worker(num):
    #recreate the Fasta object in subprocess
    fa = pyfastx.Fasta('test.fa')

    for i in random.sample(range(len(fa)), 5):
        print("worker {} print:\n{}".format(num, fa[i].raw))

# multiple process
if __name__ == '__main__':
    pool = mp.Pool()

    # execute five task workers
    for j in range(5):
        pool.apply_async(worker, args=(j,))

    pool.close()
    pool.join()
```
Example two, building index file in main process, and then pass the Fasta object directly to subprocess, and use lock to ensure only one process can fetch sequence from Fasta object each time.
```python
import random
import pyfastx
import multiprocessing as mp

# build index
fa = pyfastx.Fasta('test.fa')

# process worker
# randomly get five sequences and print
def worker(num, lock):
    #recreate the Fasta object in subprocess
    lock.acquire()
    seq = fa[i].raw
    lock.release()

    for i in random.sample(range(len(fa)), 5):
        print("worker {} print:\n{}".format(num, seq))

# multiple process
if __name__ == '__main__':
    lock = mp.Lock()
    pool = mp.Pool()

    # execute five task workers
    for j in range(5):
        pool.apply_async(worker, args=(j,lock))

    pool.close()
    pool.join()
```
The `test.fa` can be found in tests folder of source code. Hope these two simple examples can help you!

**Comment by nextgenusfs** [comment]
Thanks @lmdu for the examples.  I was trying with `apply_async` with a Fastq file, although the code was a little more complicated.  I'll try with these above examples and if I'm still having problems I will try to come up with a reproducible small example.  Again, thanks for the great tool and your continued support.
