### ISSUE TITLE
Calculate  Q30？

### ISSUE THREAD

**Issue by hjdong** [lmdu/pyfastx#16]
How to Calculate the % read >= Q30 or Q20?

Thanks!

**Comment by lmdu** [comment]
Do you mean all bases quality value >= 30 for a read >= Q30? If so, pyfastx did not directly implement this function, but you can do that like this:

```python
import pyfastx
fq = pyfastx.Fastq('your_fastq.fq')
count = 0
for r in fq:
    if all([q>=30 for q in  r.quali]):
        count += 1
percent = count/len(fq)*100
print("% read >= Q30: {}".format(percent))
```

**Comment by hjdong** [comment]
> Do you mean all bases quality value >= 30 for a read >= Q30? If so, pyfastx did not directly implement this function, but you can do that like this:
> 
> ```python
> import pyfastx
> fq = pyfastx.Fastq('your_fastq.fq')
> count = 0
> for r in fq:
>     if all([q>=30 for q in  r.quali]):
>         count += 1
> percent = count/len(fq)*100
> print("% read >= Q30: {}".format(percent))
> ```

Thank you for your help，I think I was wrong.I changed the code:
```
import pyfastx
fq = pyfastx.Fastq('your_fastq.fq')
count = 0
for r in fq:
    if [q>=30 for q in  r.quali]:
        count += 1
percent = count/fq.size*100
print("% read >= Q30: {}".format(percent))
```
But it took a long time, about 90 minutes.The file has a 5G base.
I don't know how to quickly count  Q30 percent of  base.
Thanks!

**Comment by lmdu** [comment]
To calculate Q30 bases, the program will scan all the bases quality value, it's slow. pyfastx did not provide acceleration for that. I think the tool [fastp](https://github.com/OpenGene/fastp) can meet your requirements. It was written in pure c++ and maybe faster. You can find Q30 bases percentage in its report.

**Comment by hjdong** [comment]
> To calculate Q30 bases, the program will scan all the bases quality value, it's slow. pyfastx did not provide acceleration for that. I think the tool [fastp](https://github.com/OpenGene/fastp) can meet your requirements. It was written in pure c++ and maybe faster. You can find Q30 bases percentage in its report.

Thank.I will try.
