### ISSUE TITLE
Return full sequence name without building index

### ISSUE THREAD

**Issue by cmorganl** [lmdu/pyfastx#17]
Hi Lianming,

Thank you for writing such a great tool! I'm using it in several projects I'm involved in now.

I was wondering if it is possible to return the full sequence name instead of the string split on whitespace when build_index is False? It would be great if it could be controlled using the key function as it is when an index is built. This is critical to the work that I'm doing where sequence names do not reliably have unique strings for the first part of the header.

I hope I haven't just missed something in the documentation!

Thanks!
Connor

**Comment by lmdu** [comment]
Hi Connor,

When build_index=False, pyfastx is just a kseq.h binding. kseq.h use string before first whitespace as identifier. I'm sorry for this inconvenience. I recommend you use key function to change identifier with build_index=True. The index file will be created only once. Pyfastx will not load index into memory when using index file next time.

**Comment by cmorganl** [comment]
Hi Lianming,

Thank you for your reply! I'm not having much luck with the key_func with build_index=True. Neither the Sequence.name or Sequence.description seem to be modified. Here's one of the tests I wrote:

```python
	def test_key_func(self):
		fa = pyfastx.Fasta(gzip_fasta, build_index=True, key_func=lambda x: ' '.join(x.split()[1:3]))

		for seq in fa:  # type: pyfastx.Sequence
			self.assertEqual(1, len(seq.name.split()))
```

Regarding the kseq objects, they also contain a 'comment' attribute with the remaining sequence name after the first whitespace character. Couldn't 'name' and 'comment' be combined to make the entire header again if the user wanted? I'd be happy to implement this if you're at all interested, either in a new parsing function or in index.c:pyfastx_get_next_seq().

Creating the index file requires too much time and I'm only parsing the fasta file once in my application. Specifically I need to rapidly subset sequences from the fasta file and write the subset to a new file, never using the original one again.

Thanks!

**Comment by lmdu** [comment]
Prior to using key_func to building index, you should delete the previous created index file. Of course, I have taken your advice! I added a full_name parameter to Fasta object to use full header as sequence identifier. Now you can get full name when build_index is False like this:
```python
for name, seq in pyfastx.Fasta('your_fasta.fa', build_index=False, full_name=True):
    print(name)
```
This new feature will be released with new version in later. Currently, you can download the source code and build by yourself.

Thank you for your good suggestion!

**Comment by cmorganl** [comment]
Ah, of course. I didn't notice the setUp() command in test_fasta.py was creating an index.

Excellent, thank you so much for implementing that! It is incredibly useful to my work and I hope others will find it handy as well.

**Comment by cmorganl** [comment]
Hi Lianming,

I just tested the full_name feature and it seems like if the header doesn't contain any whitespace pyfastx seg faults. Maybe it would be worth either checking whether the header contains whitespace and/or the `kseq.comment` attribute is not empty before reconstructing the full name?

Thanks for the new version supporting complete headers!

**Comment by lmdu** [comment]
Thank you for reporting this hidden bug. I will fix it in next version.
