### ISSUE TITLE
Add full_name=True option to pyfastx.Fastq

### ISSUE THREAD

**Issue by nextgenusfs** [lmdu/pyfastx#20]
Thanks again for great library -- would it be possible to add full_name=True to the Fastq parser?  ONT (nanopore) reads default as having spaces in the FASTQ header that contain useful information.  Currently, doesn't seem to be a way to keep that information as the parser seems to be truncating header at first space. 

Thanks,
Jon

**Comment by lmdu** [comment]
Thank you for your advice. In next version, I will add full_name=True to the Fastq parser.

**Comment by lmdu** [comment]
I have added full_name option to Fastq parser in latest version (0.8.1). In this version, we also added Fastx iterator for parsing fasta/q file. It will return a tuple (name, seq, qual, comment) for the fastq file, the comment is the content of header line after the first white space character.
