### ISSUE TITLE
segfaults

### ISSUE THREAD

**Issue by jyesselm** [lmdu/pyfastx#21]
I seem to be getting memory allocation issues ... I would love to use this package but not sure how to fix this.

python(9050,0x10f3a9dc0) malloc: Incorrect checksum for freed object 0x7f917f498558: probably modified after being freed.
Corrupt value: 0x0
python(9050,0x10f3a9dc0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    9050 abort      python test.py

Its always at the same read.

@FS10000899:17:BPC29511-2322:1:1101:15960:1860 2:N:0:1
GGAAGATCGAGTAGATCAAATACATACGATATGGAAGTGGGAACTACCATGCGAACGGAAACGTTCGAACTACATGGCCCACTTCCTAAGTCGTATGTAAAAGAAACAACAACAACAACCCACCATTTTGT
+
FF,,F:F,FFFF::F:F,:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFF
```
fq1 = pyfastx.Fastq("output/Mapping_Files/test_mate1_val_1.fq")
count = 0
total = 0
for r1 in fq1:
    total += 1
    print(r1.name)
    print(r1.seq)
    seq_sub = r1.seq
    found = 0
    for c in codes.values():
        if seq_sub.find(c) != -1:
            found = 1
            break
    count += 1
print(count, total)
```

**Comment by lmdu** [comment]
Thank you for reporting this issue. Would it be convenient for you to send me the test fastq file, operating system information and your python version.
