### ISSUE TITLE
How to safely close file handles with Fastx?

### ISSUE THREAD

**Issue by bjpop** [lmdu/pyfastx#27]
It is not clear how to safely close any file handles that are opened by Fastx (or any of the other classes provided by this library).

It would be nice to be able to use Fastx with contextlib for example.

**Comment by lmdu** [comment]
You don't have to worry about the opened file handle. Before Fastx object is destroyed, the opened file handle will automatically be closed by pyfastx.

**Comment by bjpop** [comment]
Fair enough, although sometimes it is useful to be able to close the file handle before waiting for GC to remove the object.

Perhaps this detail can be added to the docs?

**Comment by lmdu** [comment]
Ok, I will do that. Thank you!
