### ISSUE TITLE
iteration on record?

### ISSUE THREAD

**Issue by fmarletaz** [lmdu/pyfastx#3]
Thanks for developing pyfastx, that's a really nice tool! However, I have a basic question. When you iterate over the fasta object or the `pyfastx.Fasta(`command, does it always report name and sequences as string. What if I want to iterate over sequence objects to rename them using the description field. Maybe I missed something.  Thanks again!!!

**Comment by lmdu** [comment]
Yes, current version for fasta object iteration can only return a tuple with string of name and seq. But you can use keys for iteration to make a sequence object for additional information. For example:

```python
fa = pyfastx.Fasta('your_fasta.fa')
for name in fa.keys():
    s = fa[name]
    print(s.description)
```

In future version, iteration for sequence object from fasta object will be added.
