### ISSUE TITLE
small caps

### ISSUE THREAD

**Issue by fmarletaz** [lmdu/pyfastx#30]
Hi - 
Thanks for developing pyfastx, very useful and convenient. I had a question: how is pyfastx handling soft masked genomes with lower-case characters, such as soft-masked genomes. I notice sometimes such files generate errors or at least that everything is reverted to capital. Thanks!

**Comment by lmdu** [comment]
Hi,
You can use `uppercase=False` to output sequence appeared in FASTA file. Before version 0.8.2, uppercase was True. I have fixed it in 0.8.2. I hope this can help you.
