### ISSUE TITLE
Failure to properly parse ENCODE's GRCh38 reference

### ISSUE THREAD

**Issue by sjgosai** [lmdu/pyfastx#39]
Hello, 

I wanted to use pyfastx for some ENCODE analysis and tried to use the `Fasta` class on the GRCh38 reference found [here](https://www.encodeproject.org/data-standards/reference-sequences/) (more info [here).](https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/). When I iterate through the `fa` object I get unexpected results (i.e. the "description" from chr1 is the header for chr2). Interestingly enough, opening the file as a `Fastx` object seems to work as expected. Unfortunately, I really want to use the `fetch` method which isn't implemented for `Fastx.seq` objects.

To troubleshoot I went ahead and tested the `hg38.fa.gz` fasta from UCSC found [here](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/). Unfortunately, I'm getting odd results with this file too. For example many of the description fields are short nucleotide sequences (i.e. for chr10 i get "CGGGC").

The description field errors may not have been an issue, except when you hit the end of the Fasta file you get a `UnicodeDecodeError` when the description field is called. 

I am using version `0.8.4`.

Here is a [Google Colab notebook](https://colab.research.google.com/drive/18i93uNvPYDzNRQ4OkKKJ3IghuhxDRuxQ?usp=sharing) replicating the issue.

**Comment by lmdu** [comment]
Have you install pyfastx by pip?

**Comment by sjgosai** [comment]
Yes. I've fully reproduced the issue in the Colab notebook linked [here](https://colab.research.google.com/drive/18i93uNvPYDzNRQ4OkKKJ3IghuhxDRuxQ?usp=sharing).

**Comment by lmdu** [comment]
We have fixed this issue in new versions >= 0.9.0

**Comment by lmdu** [comment]
We have fixed this issue in new versions >= 0.9.0
