### ISSUE TITLE
Python 3.10 compatiblity

### ISSUE THREAD

**Issue by jolespin** [lmdu/pyfastx#47]
Can future versions of this incorporate Python 3.10 compatibility? The bioconda install at least requires less than 3.10

**Comment by tsibley** [comment]
We (Nextstrain) would also appreciate compat with 3.10. Ideally this would mean pyfastx's CI running on 3.10 and releasing 3.10 wheels.

@lmdu Are there known issues with 3.10 that need addressing? Would you be open to a PR adding 3.10 to the list of supported versions?

**Comment by corneliusroemer** [comment]
I've made a PR to address this issue.

#53 just upgrades a few actions in the Github workflow to allow building 3.10/11 wheels
