### ISSUE TITLE
fasta records that don't have comments have comments attached to them after conversion to tabular format

### ISSUE THREAD

**Issue by olgatsiouri1996** [lmdu/pyfastx#49]
i am running this script on miniconda with python 3.8.13 on windows 10 version 21H1( OS build 19043.1889): [fasta_to_tab_gui.py](https://gist.github.com/olgatsiouri1996/9216b314eb1eda8b5671e8b7cfc5aa91) using the 2nd option with [full.fasta](https://gist.github.com/olgatsiouri1996/b96ccfb6295d5e0f12d9ccea97510b7b) as input. So i get this weir output with fasta records that don't have comments repeating the comment of the 1st sequence: [full_tabular.txt](https://github.com/lmdu/pyfastx/files/9508693/full_tabular.txt). Is there a way to fix this?

**Comment by lmdu** [comment]
Thank you for report this bug. I have fixed it in new version

**Comment by lmdu** [comment]
We have fixed this issue in new versions >= 0.9.0
