### ISSUE TITLE
[BUG] Unable to get sequences after encountering `KeyError`

### ISSUE THREAD

**Issue by joverlee521** [lmdu/pyfastx#50]
I'm trying to access sequences with a try/except block like so:
```python
# sequences.fasta contains three sequences: 'seq_a', 'seq_b', 'seq_c'
sequences = pyfastx.Fasta('sequences.fasta')
for seq_id in ['seq_a', 'bad_sequence', 'seq_a', 'seq_b', 'seq_c']:
    try:
         sequence_record = sequences[seq_id]
     except KeyError:
         ...
```
Once I encounter a `KeyError`, all subsequent tries to get a sequence fails with a `KeyError`.
In my example, I am able to access `seq_a` the first time, but I get an error for any of the sequences after `bad_sequence`. 

Python version 3.7
pyfastx version 0.8.4

**Comment by joverlee521** [comment]
I'm not super familiar with C or the SQLite C interface, so I'm making a guess from my brief reading of the [docs](https://www.sqlite.org/c3ref/stmt.html).
It seems like there needs to be a reset with `sqlite3_reset(self->seq_stmt);` within the else block that raises the KeyError:
https://github.com/lmdu/pyfastx/blob/c5023a75ad7ef9befe8896e3d9ce9ac76c762b65/src/index.c#L536-L539

**Comment by tsibley** [comment]
Yeah, that was my assessment too. Same issue exists with integer-based indexing as well. I'm preparing a new test case and patch.

**Comment by tsibley** [comment]
https://github.com/lmdu/pyfastx/pull/51 works for me locally.
