### ISSUE TITLE
Does current pyfastx support py2.7 version?

### ISSUE THREAD

**Issue by Wan-Yifei** [lmdu/pyfastx#57]
Hi,

I want to use pyfastx in my py2.7-based project. But I don't know does pyfastx support py2.7?

Thanks!

**Comment by lmdu** [comment]
I am so sorry. Pyfastx could not support python2.7, as Python2.7 reached End Of Life at 2 years and 11 months ago.

**Comment by Wan-Yifei** [comment]
Thanks a lot!
