### ISSUE TITLE
Fastx parser vs Fasta/Fastq parsers

### ISSUE THREAD

**Issue by schorlton** [lmdu/pyfastx#61]
Hi,

Thanks for the fantastic tool! I'm trying to figure out what the difference is between `pyfastx.Fastx` and `pyfastx.Fasta(build_index=False)`/`pyfastx.Fastq(build_index=False)` for FASTA and FASTQ iteration, respectively. They seem to have almost identical functionality with slightly different arguments. Is there a performance difference? Is there any difference in validation of underlying data? Any insight is appreciated.

Thanks!

**Comment by lmdu** [comment]
The implementation of `pyfastx.Fastx` is the same with `pyfastx.Fasta(build_index=False)`. They may have the same performance. pyfastx.Fastx is a new and simple api for sequence iteration, and can detect the input sequence file format (fasta or fastq).

**Comment by schorlton** [comment]
Got it, thanks!
