### ISSUE TITLE
Writing fast

### ISSUE THREAD

**Issue by SilasK** [lmdu/pyfastx#7]
Hey @lmdu
Thank you for your package. Can you suggest an efficient way to write fasta files. 

If would need to read a fasta file and rename the headers and write them to one or multiple files. 
reading is very easy in pyfastx, but then to write it to files I found no better way than the following. 

```
        fa = pyfastx.Fasta(input.fasta)

        representatives= fa.keys()

        with open(output.faa,'w') as outf:
            for gene in fa:
                new_name= map_names[gene.name]
                lines='\n'.join(str2multiline(gene.seq))
                outf.write(">{new_name} {gene.description}\n{lines}\n")

```

If I don't need to rename I can use the seq.raw attribute but I don't know if there would be a faster way.

**Comment by lmdu** [comment]
You can replace the sequence name in header line of raw string using lstrip or replace function, like this:

```python
import pyfastx
fa = pyfastx.Fasta(input.fasta)
with open(output.faa, 'w') as fw:
    for gene in fa:
        new_name = map_names[gene.name]
        rseq = gene.raw.lstrip('>{}'.format(gene.name))
        fw.write(">{}{}".format(new_name, rseq))
```
Hope this can help you. In future, I will consider added a functionality for user to easily rename the sequence name.

**Comment by lmdu** [comment]
You can replace or rewrite the header line of raw string like this:

```python
import pyfastx
fa = pyfastx.Fasta(input.fasta)
representatives= fa.keys()
with open(output.faa,'w') as outf:
    for gene in fa:
        new_name= map_names[gene.name]
        rseq = gene.raw.lstrip('>{}'.format(gene.name))
        outf.write(">{}{}".format(new_name, rseq))
```

Hope this code can help you. In later version, I may add a functionality to help users to easily rename sequence.

**Comment by SilasK** [comment]
I wondered how complicated it is to make some c-accelerated writing.

**Comment by lmdu** [comment]
Sorry, I'm not sure it's necessary to accelerate writing by using C. Because, the Python IO is comparable with C language. There are several reasons for me to use cpython (not cython) for accelerating reading sequence. 1) more time needed to build index by using python; 2) to resolve random access from gzipped sequence file; 3) python double memory when uppercase large sequence.
