### ISSUE TITLE
get seq count and length error

### ISSUE THREAD

**Issue by SilasK** [lmdu/pyfastx#9]
I got an error in pyfastx 0.6.5 installed with conda on a linux system

```

>>> import pyfastx
>>> fa=pyfastx.Fasta('all_bins/ERR2059947_metabat_58.fasta')
RuntimeError: get seq count and length error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'Fasta'> returned a result with an error set

```

**Comment by lmdu** [comment]
I have not previously used conda to install pyfastx. But I am sure conda did not provide precompiled wheel for pyfastx.  pyfastx install with conda will trigger compiling process. Thus, you should make sure   zlib and sqlite3 library have been correctly installed on your linux system. I recommend you use pip to install pyfastx. Certainly, I will take the time to make it support for conda in future.

**Comment by maximilianmordig** [comment]
The issue persists, even after deleting the index file (`fxi` file)
`curl https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz -O`.
It seems to be related to the index though:
```
import pyfastx; pyfastx.Fasta("chm13v2.0.fa.gz", build_index=False)
```
works, but
```
import pyfastx; pyfastx.Fasta("chm13v2.0.fa.gz")
```
does not.
